pid = /var/run/stunnel.pid
foreground = yes
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

[kavkom]
client = yes
accept = 127.0.0.1:15062
connect = aria-madacom.kavkom.com:5061
sni = aria-madacom.kavkom.com
verifyChain = yes
CApath = /etc/ssl/certs
