[supervisord]
nodaemon=true

[program:laravel-worker]
process_name=%(program_name)s
autostart=true
command=/usr/local/bin/php artisan queue:work --queue='emails,google_calendar,google_contact,google_drive,google_map,imports,sms,default' --sleep=3 --tries=3 --timeout=0 --memory=128
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
stopwaitsecs=3600

[program:laravel-scheduler]
process_name=%(program_name)s
autostart=true
command='/usr/local/bin/php' 'artisan' schedule:work
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/scheduler.log
stopwaitsecs=3600