[supervisord]
nodaemon=true

[program:laravel-worker]
process_name=%(program_name)s
autostart=true
command=/usr/local/bin/php artisan queue:work --queue='emails,google_calendar,google_contact,google_drive,google_map,sms,default' --sleep=1 --tries=3 --timeout=0 --memory=128 --max-time=300
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
stopwaitsecs=3600

[program:laravel-worker-imports]
process_name=%(program_name)s_%(process_num)02d
autostart=true
command=/usr/local/bin/php -d memory_limit=512M artisan queue:work --queue='imports' --sleep=1 --tries=3 --timeout=0 --memory=400 --max-time=300
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-imports.log
stopwaitsecs=3600

[program:laravel-scheduler]
process_name=%(program_name)s
autostart=true
command='/usr/local/bin/php' 'artisan' schedule:work
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/scheduler.log
stopwaitsecs=3600