[supervisord]
nodaemon=true

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
autostart=true
command='/usr/local/bin/php' 'artisan' queue:work '' --once --queue='emails,google_calendar,google_contact,google_drive,google_map,imports,sms,default' --delay=0 --memory=128 --sleep=3 --tries=3 --timeout=0
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
stopwaitsecs=3600