[transport-tls]
type=transport
protocol=${KAVKOM_SIP_TRANSPORT}
bind=0.0.0.0:${KAVKOM_SIP_PORT}

[kavkom-reg]
type=registration
outbound_auth=kavkom-auth
server_uri=sip:${KAVKOM_USER_CONTEXT}:${KAVKOM_SIP_PORT}
client_uri=sip:${KAVKOM_EXTENSION}@${KAVKOM_USER_CONTEXT}
transport=transport-tls
retry_interval=60
expiration=3600

[kavkom-auth]
type=auth
auth_type=userpass
username=${KAVKOM_EXTENSION}
password=${KAVKOM_PASSWORD}

[kavkom-trunk]
type=endpoint
context=from-kavkom
transport=transport-tls
disallow=all
allow=alaw,ulaw
outbound_auth=kavkom-auth
aors=kavkom-aor
direct_media=no

[kavkom-aor]
type=aor
contact=sip:${KAVKOM_USER_CONTEXT}:${KAVKOM_SIP_PORT}

[kavkom-identify]
type=identify
endpoint=kavkom-trunk
match=${KAVKOM_USER_CONTEXT}