/**
 * ISO 3166-1 alpha-2 code + E.164 dial code for every country. The flag is
 * derived from the code (each letter maps to a Unicode regional indicator
 * symbol) rather than typed by hand, so the list stays easy to extend
 * without risking a wrong emoji.
 */
function flagFromCode(code) {
    return code
        .toUpperCase()
        .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

const countries = [
    { code: "AD", label: "Andorre", dial_code: "376" },
    { code: "AE", label: "Émirats arabes unis", dial_code: "971" },
    { code: "AF", label: "Afghanistan", dial_code: "93" },
    { code: "AG", label: "Antigua-et-Barbuda", dial_code: "1" },
    { code: "AL", label: "Albanie", dial_code: "355" },
    { code: "AM", label: "Arménie", dial_code: "374" },
    { code: "AO", label: "Angola", dial_code: "244" },
    { code: "AR", label: "Argentine", dial_code: "54" },
    { code: "AT", label: "Autriche", dial_code: "43" },
    { code: "AU", label: "Australie", dial_code: "61" },
    { code: "AZ", label: "Azerbaïdjan", dial_code: "994" },
    { code: "BA", label: "Bosnie-Herzégovine", dial_code: "387" },
    { code: "BB", label: "Barbade", dial_code: "1" },
    { code: "BD", label: "Bangladesh", dial_code: "880" },
    { code: "BE", label: "Belgique", dial_code: "32" },
    { code: "BF", label: "Burkina Faso", dial_code: "226" },
    { code: "BG", label: "Bulgarie", dial_code: "359" },
    { code: "BH", label: "Bahreïn", dial_code: "973" },
    { code: "BI", label: "Burundi", dial_code: "257" },
    { code: "BJ", label: "Bénin", dial_code: "229" },
    { code: "BN", label: "Brunei", dial_code: "673" },
    { code: "BO", label: "Bolivie", dial_code: "591" },
    { code: "BR", label: "Brésil", dial_code: "55" },
    { code: "BS", label: "Bahamas", dial_code: "1" },
    { code: "BT", label: "Bhoutan", dial_code: "975" },
    { code: "BW", label: "Botswana", dial_code: "267" },
    { code: "BY", label: "Biélorussie", dial_code: "375" },
    { code: "BZ", label: "Belize", dial_code: "501" },
    { code: "CA", label: "Canada", dial_code: "1" },
    { code: "CD", label: "République démocratique du Congo", dial_code: "243" },
    { code: "CF", label: "République centrafricaine", dial_code: "236" },
    { code: "CG", label: "Congo-Brazzaville", dial_code: "242" },
    { code: "CH", label: "Suisse", dial_code: "41" },
    { code: "CI", label: "Côte d'Ivoire", dial_code: "225" },
    { code: "CL", label: "Chili", dial_code: "56" },
    { code: "CM", label: "Cameroun", dial_code: "237" },
    { code: "CN", label: "Chine", dial_code: "86" },
    { code: "CO", label: "Colombie", dial_code: "57" },
    { code: "CR", label: "Costa Rica", dial_code: "506" },
    { code: "CU", label: "Cuba", dial_code: "53" },
    { code: "CV", label: "Cap-Vert", dial_code: "238" },
    { code: "CY", label: "Chypre", dial_code: "357" },
    { code: "CZ", label: "République tchèque", dial_code: "420" },
    { code: "DE", label: "Allemagne", dial_code: "49" },
    { code: "DJ", label: "Djibouti", dial_code: "253" },
    { code: "DK", label: "Danemark", dial_code: "45" },
    { code: "DM", label: "Dominique", dial_code: "1" },
    { code: "DO", label: "République dominicaine", dial_code: "1" },
    { code: "DZ", label: "Algérie", dial_code: "213" },
    { code: "EC", label: "Équateur", dial_code: "593" },
    { code: "EE", label: "Estonie", dial_code: "372" },
    { code: "EG", label: "Égypte", dial_code: "20" },
    { code: "ER", label: "Érythrée", dial_code: "291" },
    { code: "ES", label: "Espagne", dial_code: "34" },
    { code: "ET", label: "Éthiopie", dial_code: "251" },
    { code: "FI", label: "Finlande", dial_code: "358" },
    { code: "FJ", label: "Fidji", dial_code: "679" },
    { code: "FM", label: "Micronésie", dial_code: "691" },
    { code: "FO", label: "Îles Féroé", dial_code: "298" },
    { code: "FR", label: "France", dial_code: "33" },
    { code: "GA", label: "Gabon", dial_code: "241" },
    { code: "GB", label: "Royaume-Uni", dial_code: "44" },
    { code: "GD", label: "Grenade", dial_code: "1" },
    { code: "GE", label: "Géorgie", dial_code: "995" },
    { code: "GH", label: "Ghana", dial_code: "233" },
    { code: "GI", label: "Gibraltar", dial_code: "350" },
    { code: "GL", label: "Groenland", dial_code: "299" },
    { code: "GM", label: "Gambie", dial_code: "220" },
    { code: "GN", label: "Guinée", dial_code: "224" },
    { code: "GQ", label: "Guinée équatoriale", dial_code: "240" },
    { code: "GR", label: "Grèce", dial_code: "30" },
    { code: "GT", label: "Guatemala", dial_code: "502" },
    { code: "GW", label: "Guinée-Bissau", dial_code: "245" },
    { code: "GY", label: "Guyana", dial_code: "592" },
    { code: "HK", label: "Hong Kong", dial_code: "852" },
    { code: "HN", label: "Honduras", dial_code: "504" },
    { code: "HR", label: "Croatie", dial_code: "385" },
    { code: "HT", label: "Haïti", dial_code: "509" },
    { code: "HU", label: "Hongrie", dial_code: "36" },
    { code: "ID", label: "Indonésie", dial_code: "62" },
    { code: "IE", label: "Irlande", dial_code: "353" },
    { code: "IL", label: "Israël", dial_code: "972" },
    { code: "IN", label: "Inde", dial_code: "91" },
    { code: "IQ", label: "Irak", dial_code: "964" },
    { code: "IR", label: "Iran", dial_code: "98" },
    { code: "IS", label: "Islande", dial_code: "354" },
    { code: "IT", label: "Italie", dial_code: "39" },
    { code: "JM", label: "Jamaïque", dial_code: "1" },
    { code: "JO", label: "Jordanie", dial_code: "962" },
    { code: "JP", label: "Japon", dial_code: "81" },
    { code: "KE", label: "Kenya", dial_code: "254" },
    { code: "KG", label: "Kirghizistan", dial_code: "996" },
    { code: "KH", label: "Cambodge", dial_code: "855" },
    { code: "KI", label: "Kiribati", dial_code: "686" },
    { code: "KM", label: "Comores", dial_code: "269" },
    { code: "KN", label: "Saint-Christophe-et-Niévès", dial_code: "1" },
    { code: "KP", label: "Corée du Nord", dial_code: "850" },
    { code: "KR", label: "Corée du Sud", dial_code: "82" },
    { code: "KW", label: "Koweït", dial_code: "965" },
    { code: "KZ", label: "Kazakhstan", dial_code: "7" },
    { code: "LA", label: "Laos", dial_code: "856" },
    { code: "LB", label: "Liban", dial_code: "961" },
    { code: "LC", label: "Sainte-Lucie", dial_code: "1" },
    { code: "LI", label: "Liechtenstein", dial_code: "423" },
    { code: "LK", label: "Sri Lanka", dial_code: "94" },
    { code: "LR", label: "Liberia", dial_code: "231" },
    { code: "LS", label: "Lesotho", dial_code: "266" },
    { code: "LT", label: "Lituanie", dial_code: "370" },
    { code: "LU", label: "Luxembourg", dial_code: "352" },
    { code: "LV", label: "Lettonie", dial_code: "371" },
    { code: "LY", label: "Libye", dial_code: "218" },
    { code: "MA", label: "Maroc", dial_code: "212" },
    { code: "MC", label: "Monaco", dial_code: "377" },
    { code: "MD", label: "Moldavie", dial_code: "373" },
    { code: "ME", label: "Monténégro", dial_code: "382" },
    { code: "MG", label: "Madagascar", dial_code: "261" },
    { code: "MH", label: "Îles Marshall", dial_code: "692" },
    { code: "MK", label: "Macédoine du Nord", dial_code: "389" },
    { code: "ML", label: "Mali", dial_code: "223" },
    { code: "MM", label: "Birmanie", dial_code: "95" },
    { code: "MN", label: "Mongolie", dial_code: "976" },
    { code: "MO", label: "Macao", dial_code: "853" },
    { code: "MR", label: "Mauritanie", dial_code: "222" },
    { code: "MT", label: "Malte", dial_code: "356" },
    { code: "MU", label: "Maurice", dial_code: "230" },
    { code: "MV", label: "Maldives", dial_code: "960" },
    { code: "MW", label: "Malawi", dial_code: "265" },
    { code: "MX", label: "Mexique", dial_code: "52" },
    { code: "MY", label: "Malaisie", dial_code: "60" },
    { code: "MZ", label: "Mozambique", dial_code: "258" },
    { code: "NA", label: "Namibie", dial_code: "264" },
    { code: "NC", label: "Nouvelle-Calédonie", dial_code: "687" },
    { code: "NE", label: "Niger", dial_code: "227" },
    { code: "NG", label: "Nigeria", dial_code: "234" },
    { code: "NI", label: "Nicaragua", dial_code: "505" },
    { code: "NL", label: "Pays-Bas", dial_code: "31" },
    { code: "NO", label: "Norvège", dial_code: "47" },
    { code: "NP", label: "Népal", dial_code: "977" },
    { code: "NR", label: "Nauru", dial_code: "674" },
    { code: "NZ", label: "Nouvelle-Zélande", dial_code: "64" },
    { code: "OM", label: "Oman", dial_code: "968" },
    { code: "PA", label: "Panama", dial_code: "507" },
    { code: "PE", label: "Pérou", dial_code: "51" },
    { code: "PF", label: "Polynésie française", dial_code: "689" },
    { code: "PG", label: "Papouasie-Nouvelle-Guinée", dial_code: "675" },
    { code: "PH", label: "Philippines", dial_code: "63" },
    { code: "PK", label: "Pakistan", dial_code: "92" },
    { code: "PL", label: "Pologne", dial_code: "48" },
    { code: "PR", label: "Porto Rico", dial_code: "1" },
    { code: "PS", label: "Palestine", dial_code: "970" },
    { code: "PT", label: "Portugal", dial_code: "351" },
    { code: "PW", label: "Palaos", dial_code: "680" },
    { code: "PY", label: "Paraguay", dial_code: "595" },
    { code: "QA", label: "Qatar", dial_code: "974" },
    { code: "RE", label: "La Réunion", dial_code: "262" },
    { code: "RO", label: "Roumanie", dial_code: "40" },
    { code: "RS", label: "Serbie", dial_code: "381" },
    { code: "RU", label: "Russie", dial_code: "7" },
    { code: "RW", label: "Rwanda", dial_code: "250" },
    { code: "SA", label: "Arabie saoudite", dial_code: "966" },
    { code: "SB", label: "Îles Salomon", dial_code: "677" },
    { code: "SC", label: "Seychelles", dial_code: "248" },
    { code: "SD", label: "Soudan", dial_code: "249" },
    { code: "SE", label: "Suède", dial_code: "46" },
    { code: "SG", label: "Singapour", dial_code: "65" },
    { code: "SI", label: "Slovénie", dial_code: "386" },
    { code: "SK", label: "Slovaquie", dial_code: "421" },
    { code: "SL", label: "Sierra Leone", dial_code: "232" },
    { code: "SM", label: "Saint-Marin", dial_code: "378" },
    { code: "SN", label: "Sénégal", dial_code: "221" },
    { code: "SO", label: "Somalie", dial_code: "252" },
    { code: "SR", label: "Suriname", dial_code: "597" },
    { code: "SS", label: "Soudan du Sud", dial_code: "211" },
    { code: "ST", label: "Sao Tomé-et-Principe", dial_code: "239" },
    { code: "SV", label: "Salvador", dial_code: "503" },
    { code: "SY", label: "Syrie", dial_code: "963" },
    { code: "SZ", label: "Eswatini", dial_code: "268" },
    { code: "TD", label: "Tchad", dial_code: "235" },
    { code: "TG", label: "Togo", dial_code: "228" },
    { code: "TH", label: "Thaïlande", dial_code: "66" },
    { code: "TJ", label: "Tadjikistan", dial_code: "992" },
    { code: "TL", label: "Timor oriental", dial_code: "670" },
    { code: "TM", label: "Turkménistan", dial_code: "993" },
    { code: "TN", label: "Tunisie", dial_code: "216" },
    { code: "TO", label: "Tonga", dial_code: "676" },
    { code: "TR", label: "Turquie", dial_code: "90" },
    { code: "TT", label: "Trinité-et-Tobago", dial_code: "1" },
    { code: "TV", label: "Tuvalu", dial_code: "688" },
    { code: "TW", label: "Taïwan", dial_code: "886" },
    { code: "TZ", label: "Tanzanie", dial_code: "255" },
    { code: "UA", label: "Ukraine", dial_code: "380" },
    { code: "UG", label: "Ouganda", dial_code: "256" },
    { code: "US", label: "États-Unis", dial_code: "1" },
    { code: "UY", label: "Uruguay", dial_code: "598" },
    { code: "UZ", label: "Ouzbékistan", dial_code: "998" },
    { code: "VA", label: "Vatican", dial_code: "379" },
    { code: "VC", label: "Saint-Vincent-et-les-Grenadines", dial_code: "1" },
    { code: "VE", label: "Venezuela", dial_code: "58" },
    { code: "VN", label: "Viêt Nam", dial_code: "84" },
    { code: "VU", label: "Vanuatu", dial_code: "678" },
    { code: "WS", label: "Samoa", dial_code: "685" },
    { code: "XK", label: "Kosovo", dial_code: "383" },
    { code: "YE", label: "Yémen", dial_code: "967" },
    { code: "YT", label: "Mayotte", dial_code: "262" },
    { code: "ZA", label: "Afrique du Sud", dial_code: "27" },
    { code: "ZM", label: "Zambie", dial_code: "260" },
    { code: "ZW", label: "Zimbabwe", dial_code: "263" },
];

export default countries
    .map((country) => ({ ...country, flag: flagFromCode(country.code) }))
    .sort((a, b) => a.label.localeCompare(b.label, "fr"));
